FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy source code
COPY . .

# Environment variables for dev
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV development

# Expose port
EXPOSE 3000

# Start dev server
CMD ["npm", "run", "dev"]
